### ISSUE TITLE
deploy database - download process

### ISSUE THREAD

**Issue by jimthereaper** [vfeedio/pyvfeed#1]
{
  "object": "boto3.session",
  "status": "No module named ",
  "success": false
}

Hi, 
I'm trying to do a first run using Kali Linux (vmware box) and it gives me the error above. The config.py file saved is as follows:

database = {"file": 'vfeed.db',
            "path": '/root/Documents/testDB/',
            }

export = {"path": '/root/Documents/export/'}

subscription = {"access_key": 'XXXXXX',
                "secret_key": 'XXXXXXXXX',
                "plan": 'vfeed-demo'
                }

Can someone throw some insights?

**Comment by toolswatch** [comment]
My first question is Do you have an API key ?
Second one..did you install the requirements ! I see boto is missed.

**Comment by jimthereaper** [comment]
Yes, I have the API keys - just XXXXX'ed it here.

used the command  - python setup.py install to install boto3
while installing pyyaml using the same command gave me:
x86_64-linux-gnu-gcc: error: ext/_yaml.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
after that it ran this:  running install_lib

**Comment by toolswatch** [comment]
Here is the doc https://github.com/vfeedio/pyvfeed/wiki/2)-Getting-started

Try this
sudo python3 -m pip install -r requirements.txt

**Comment by toolswatch** [comment]
Did you try this sudo python3 -m pip install -r requirements.txt ?

**Comment by jimthereaper** [comment]
Apology for the late response. Yes, I did now, it returned this:  

root@kali:~/pyvfeed# **sudo python3 -m pip install -r requirements.txt**
/usr/bin/python3: No module named pip

After this error I used: **sudo apt-get install python3-pip** to install pip and then tried again: **sudo python3 -m pip install -r requirements.txt** it worked **Successfully installed boto3-1.7.4 botocore-1.10.10 docutils-0.14 jmespath-0.9.3 s3transfer-0.1.13**

**Comment by jimthereaper** [comment]
So now, I've tried to deploy the database using the command and throws the error. 

root@kali:~/pyvfeed# **./pyvfeed.py --update**
{
  "object": "Error on secret key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "status": "An error occurred (SignatureDoesNotMatch) when calling the ListObjects operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.",
  "success": false
}

**Comment by toolswatch** [comment]
Can you send me to "support@vfeed.io"  the APIs you got (both Access and Secret keys).

Did you resolve "/usr/bin/python3: No module named pip" ...  this is related to pip not to vfeed. Maybe this will fix it python3 -m ensurepip --upgrade

**Comment by jimthereaper** [comment]
Yes, I've resolved **/usr/bin/python3: No module named pip**  using **sudo apt-get install python3-pip**
Check your email, the API keys.

**Comment by jimthereaper** [comment]
database deployed successfully using **./pyvfeed.py --update** after the correction.
