### ISSUE TITLE
API Installation - Requirements - boto3 >> Windows OS

### ISSUE THREAD

**Issue by jimthereaper** [vfeedio/pyvfeed#3]
Hi there, 

Now I am trying to get started on a windows 10 machine using Python 3.6.1 |Anaconda 4.4.0 (64-bit)|. 
I've installed pip first and pyyaml also installed fine but while installing boto3 using **pip install boto3** I'm getting below error. Any suggestions?

![boto3](https://user-images.githubusercontent.com/34950697/39818672-bf4db608-53a1-11e8-80bc-d1ec79c137fe.PNG)

**Comment by toolswatch** [comment]
I see. Maybe try  
**python3 -m pip install boto3**

**Comment by jimthereaper** [comment]
Thanks but didn't work using **python3 -m pip install boto3** . 

So, used this **netsh winhttp show proxy** to get the proxy details and then bypass if for the installation boto3 using **pip --proxy proxy.server:port install boto3** 

Note: **proxy.server:port** needs to be completed with the details of the proxy.

![bypass_proxy](https://user-images.githubusercontent.com/34950697/39821697-0e4c091a-53a9-11e8-862f-1890f3b73fd7.PNG)

**Comment by jthompson88** [comment]
I had similar problem, buddy. 

I see you are using python3. Try pip3 install boto3.
