### ISSUE TITLE
CVSS algorithm

### ISSUE THREAD

**Issue by jimthereaper** [vfeedio/pyvfeed#4]
Can you help us achieve a custom (for example: risk.py) python file which can be run using your API? 
Note: This .py file can be modified according to our internal risk assessment scores.

[vFeed_API.docx](https://github.com/vfeedio/pyvfeed/files/1991650/vFeed_API.docx)

**Comment by vfeedio** [comment]
Hi,
Can you send me an email to explain more. 

Regards

NJ/
